services:
  postgres:
    image: postgres:16
    container_name: iracing-postgres
    environment:
      POSTGRES_USER: iracing
      POSTGRES_PASSWORD: iracing_local
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: iracing-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pgdata: