"""add file_name and file_hash to Session

Revision ID: 20f1d1a9a438
Revises: d7eae3ef9ded
Create Date: 2026-07-20 13:27:33.729878

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20f1d1a9a438"
down_revision: Union[str, Sequence[str], None] = "d7eae3ef9ded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("file_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_sessions_file_hash"), "sessions", ["file_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_file_hash"), table_name="sessions")
    op.drop_column("sessions", "file_hash")
    # ### end Alembic commands ###
