"""add created_at to sessions

Revision ID: 2a00451848a6
Revises: 20f1d1a9a438
Create Date: 2026-07-31 11:46:14.855894

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a00451848a6"
down_revision: Union[str, Sequence[str], None] = "20f1d1a9a438"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("laps", "session_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_laps_lap_time"), "laps", ["lap_time"], unique=False)
    op.create_index(op.f("ix_laps_session_id"), "laps", ["session_id"], unique=False)
    op.alter_column("sectors", "lap_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_sectors_lap_id"), "sectors", ["lap_id"], unique=False)
    op.add_column("sessions", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.alter_column("sessions", "player_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_sessions_player_id"), "sessions", ["player_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_player_id"), table_name="sessions")
    op.alter_column("sessions", "player_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("sessions", "created_at")
    op.drop_index(op.f("ix_sectors_lap_id"), table_name="sectors")
    op.alter_column("sectors", "lap_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f("ix_laps_session_id"), table_name="laps")
    op.drop_index(op.f("ix_laps_lap_time"), table_name="laps")
    op.alter_column("laps", "session_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
