"""initial_schema

Revision ID: 473a33105f2e
Revises:
Create Date: 2026-07-16 10:18:29.963111

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473a33105f2e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("track_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_table(
        "laps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("lap_number", sa.Integer(), nullable=True),
        sa.Column("lap_time", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lap_id", sa.Integer(), nullable=True),
        sa.Column("sector_number", sa.Integer(), nullable=True),
        sa.Column("sector_time", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lap_id"],
            ["laps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lap_id", sa.Integer(), nullable=True),
        sa.Column("session_time", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("gear", sa.Integer(), nullable=True),
        sa.Column("throttle", sa.Float(), nullable=True),
        sa.Column("brake", sa.Float(), nullable=True),
        sa.Column("wheel_angle", sa.Float(), nullable=True),
        sa.Column("lap_dist_pct", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat_accel", sa.Float(), nullable=True),
        sa.Column("long_accel", sa.Float(), nullable=True),
        sa.Column("yaw_rate", sa.Float(), nullable=True),
        sa.Column("velocity_x", sa.Float(), nullable=True),
        sa.Column("velocity_z", sa.Float(), nullable=True),
        sa.Column("slip_angle", sa.Float(), nullable=True),
        sa.Column("lf_speed", sa.Float(), nullable=True),
        sa.Column("rf_speed", sa.Float(), nullable=True),
        sa.Column("lr_speed", sa.Float(), nullable=True),
        sa.Column("rr_speed", sa.Float(), nullable=True),
        sa.Column("abs_active", sa.Float(), nullable=True),
        sa.Column("tc_active", sa.Float(), nullable=True),
        sa.Column("wheel_lock", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lap_id"],
            ["laps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telemetry")
    op.drop_table("sectors")
    op.drop_table("laps")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
