"""add ondelete cascade to foreign keys

Revision ID: 5458c2ba20aa
Revises: b0acf5c704cb
Create Date: 2026-09-01 14:51:18.984665

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5458c2ba20aa"
down_revision: Union[str, Sequence[str], None] = "b0acf5c704cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
