"""add track_length to sessions

Revision ID: 58223e2f9afa
Revises: 34890ff891fd
Create Date: 2026-09-01 14:42:16.266373

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58223e2f9afa"
down_revision: Union[str, Sequence[str], None] = "34890ff891fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("track_length", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "track_length")
    # ### end Alembic commands ###
