"""add_car_name_start_time_duration_to_sessions

Revision ID: 62347447d1b6
Revises: 2a00451848a6
Create Date: 2026-07-31 12:44:52.645965

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62347447d1b6"
down_revision: Union[str, Sequence[str], None] = "2a00451848a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("car_name", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("start_time", sa.DateTime(), nullable=True))
    op.add_column("sessions", sa.Column("duration_seconds", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "duration_seconds")
    op.drop_column("sessions", "start_time")
    op.drop_column("sessions", "car_name")
    # ### end Alembic commands ###
