"""add ondelete cascade to foreign keys

Revision ID: b0acf5c704cb
Revises: 58223e2f9afa
Create Date: 2026-09-01 14:50:27.373812

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0acf5c704cb"
down_revision: Union[str, Sequence[str], None] = "58223e2f9afa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("laps_session_id_fkey"), "laps", type_="foreignkey")
    op.create_foreign_key(None, "laps", "sessions", ["session_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("sectors_lap_id_fkey"), "sectors", type_="foreignkey")
    op.create_foreign_key(None, "sectors", "laps", ["lap_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("sessions_player_id_fkey"), "sessions", type_="foreignkey")
    op.create_foreign_key(None, "sessions", "players", ["player_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("telemetry_lap_id_fkey"), "telemetry", type_="foreignkey")
    op.create_foreign_key(None, "telemetry", "laps", ["lap_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telemetry", type_="foreignkey")
    op.create_foreign_key(op.f("telemetry_lap_id_fkey"), "telemetry", "laps", ["lap_id"], ["id"])
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("sessions_player_id_fkey"), "sessions", "players", ["player_id"], ["id"]
    )
    op.drop_constraint(None, "sectors", type_="foreignkey")
    op.create_foreign_key(op.f("sectors_lap_id_fkey"), "sectors", "laps", ["lap_id"], ["id"])
    op.drop_constraint(None, "laps", type_="foreignkey")
    op.create_foreign_key(op.f("laps_session_id_fkey"), "laps", "sessions", ["session_id"], ["id"])
    # ### end Alembic commands ###
