"""add track_id

Revision ID: b7418bb4f61d
Revises: 62347447d1b6
Create Date: 2026-08-07 12:08:14.978848

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b7418bb4f61d"
down_revision: Union[str, Sequence[str], None] = "62347447d1b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
