"""add file_name and file_hash to Session

Revision ID: d7eae3ef9ded
Revises: ac1feb5b739f
Create Date: 2026-07-20 13:26:57.401659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eae3ef9ded'
down_revision: Union[str, Sequence[str], None] = 'ac1feb5b739f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_telemetry_lap_id'), 'telemetry', ['lap_id'], unique=False)
    op.create_index(op.f('ix_telemetry_session_time'), 'telemetry', ['session_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_session_time'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_lap_id'), table_name='telemetry')
    # ### end Alembic commands ###
