import json
import os

tracks_dir = os.path.join("data", "tracks")
os.makedirs(tracks_dir, exist_ok=True)

tracks = [
    {
        "track_name": "tsukuba_2000",
        "display_name": "Tsukuba Circuit - Course 2000",
        "length_m": 2045.0,
        "aliases": ["tsukuba", "tsukuba 2000", "tsukuba 2kfull", "tsukuba circuit", "tsukuba_full"],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - First Hairpin",
                "start_pct": 0.04,
                "apex_pct": 0.11,
                "end_pct": 0.17,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 2,
                "name": "Turn 2 - S-Curve Entry",
                "start_pct": 0.18,
                "apex_pct": 0.23,
                "end_pct": 0.27,
                "turn_type": "corner",
            },
            {
                "turn_number": 3,
                "name": "Turn 3 - S-Curve Exit",
                "start_pct": 0.28,
                "apex_pct": 0.32,
                "end_pct": 0.36,
                "turn_type": "corner",
            },
            {
                "turn_number": 4,
                "name": "Turn 4 - Dunlop Curve",
                "start_pct": 0.37,
                "apex_pct": 0.41,
                "end_pct": 0.47,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - 80R Sweeper",
                "start_pct": 0.48,
                "apex_pct": 0.52,
                "end_pct": 0.56,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - Second Hairpin",
                "start_pct": 0.56,
                "apex_pct": 0.60,
                "end_pct": 0.68,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - Back Straight Kink",
                "start_pct": 0.69,
                "apex_pct": 0.73,
                "end_pct": 0.78,
                "turn_type": "kink",
            },
            {
                "turn_number": 8,
                "name": "Turn 8 - Final Corner Sweeper",
                "start_pct": 0.82,
                "apex_pct": 0.91,
                "end_pct": 0.98,
                "turn_type": "sweeper",
            },
        ],
    },
    {
        "track_name": "spa_gp",
        "display_name": "Circuit de Spa-Francorchamps",
        "length_m": 7004.0,
        "aliases": [
            "spa",
            "spa-francorchamps",
            "spa gp",
            "circuit de spa-francorchamps",
            "spa combined",
        ],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - La Source",
                "start_pct": 0.01,
                "apex_pct": 0.04,
                "end_pct": 0.07,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 2,
                "name": "Turn 2-4 - Eau Rouge / Raidillon",
                "start_pct": 0.10,
                "apex_pct": 0.13,
                "end_pct": 0.17,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 5,
                "name": "Turn 5-6 - Les Combes",
                "start_pct": 0.29,
                "apex_pct": 0.32,
                "end_pct": 0.35,
                "turn_type": "chicane",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - Malmedy",
                "start_pct": 0.35,
                "apex_pct": 0.37,
                "end_pct": 0.40,
                "turn_type": "corner",
            },
            {
                "turn_number": 8,
                "name": "Turn 8 - Bruxelles",
                "start_pct": 0.41,
                "apex_pct": 0.44,
                "end_pct": 0.47,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 9,
                "name": "Turn 9 - Speaker Corner",
                "start_pct": 0.47,
                "apex_pct": 0.50,
                "end_pct": 0.53,
                "turn_type": "corner",
            },
            {
                "turn_number": 10,
                "name": "Turn 10-11 - Pouhon (Double Gauche)",
                "start_pct": 0.55,
                "apex_pct": 0.59,
                "end_pct": 0.64,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 12,
                "name": "Turn 12-13 - Fagnes (Pif-Paf)",
                "start_pct": 0.67,
                "apex_pct": 0.70,
                "end_pct": 0.74,
                "turn_type": "chicane",
            },
            {
                "turn_number": 14,
                "name": "Turn 14-15 - Campus & Stavelot",
                "start_pct": 0.75,
                "apex_pct": 0.78,
                "end_pct": 0.82,
                "turn_type": "corner",
            },
            {
                "turn_number": 16,
                "name": "Turn 16-17 - Blanchimont",
                "start_pct": 0.88,
                "apex_pct": 0.91,
                "end_pct": 0.94,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 18,
                "name": "Turn 18-19 - Bus Stop Chicane",
                "start_pct": 0.95,
                "apex_pct": 0.97,
                "end_pct": 0.99,
                "turn_type": "chicane",
            },
        ],
    },
    {
        "track_name": "okayama_full",
        "display_name": "Okayama International Circuit - Full",
        "length_m": 3703.0,
        "aliases": [
            "okayama",
            "okayama full",
            "okayama international",
            "okayama international circuit",
        ],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - First Corner",
                "start_pct": 0.05,
                "apex_pct": 0.08,
                "end_pct": 0.12,
                "turn_type": "corner",
            },
            {
                "turn_number": 2,
                "name": "Turn 2 - Williams Corner",
                "start_pct": 0.13,
                "apex_pct": 0.16,
                "end_pct": 0.20,
                "turn_type": "corner",
            },
            {
                "turn_number": 3,
                "name": "Turn 3 - Moss S-Curves",
                "start_pct": 0.24,
                "apex_pct": 0.28,
                "end_pct": 0.32,
                "turn_type": "chicane",
            },
            {
                "turn_number": 4,
                "name": "Turn 4 - Attwood Curve",
                "start_pct": 0.33,
                "apex_pct": 0.37,
                "end_pct": 0.42,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - Hairpin Corner",
                "start_pct": 0.50,
                "apex_pct": 0.54,
                "end_pct": 0.58,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - Revolver Corner",
                "start_pct": 0.60,
                "apex_pct": 0.64,
                "end_pct": 0.68,
                "turn_type": "corner",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - Piper Corner",
                "start_pct": 0.69,
                "apex_pct": 0.72,
                "end_pct": 0.76,
                "turn_type": "corner",
            },
            {
                "turn_number": 8,
                "name": "Turn 8 - Redman Corner",
                "start_pct": 0.77,
                "apex_pct": 0.81,
                "end_pct": 0.84,
                "turn_type": "corner",
            },
            {
                "turn_number": 9,
                "name": "Turn 9 - Hobbs Corner",
                "start_pct": 0.85,
                "apex_pct": 0.88,
                "end_pct": 0.91,
                "turn_type": "corner",
            },
            {
                "turn_number": 10,
                "name": "Turn 10 - Mike Knight Corner",
                "start_pct": 0.92,
                "apex_pct": 0.95,
                "end_pct": 0.98,
                "turn_type": "corner",
            },
        ],
    },
    {
        "track_name": "watkins_glen_full",
        "display_name": "Watkins Glen International - Full Course",
        "length_m": 5430.0,
        "aliases": [
            "watkins glen",
            "watkinsglen",
            "watkinsglen 2021 fullcourse",
            "watkins glen full",
            "watkinsglen fullcourse",
            "watkins glen boot",
        ],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - The Ninety",
                "start_pct": 0.05,
                "apex_pct": 0.09,
                "end_pct": 0.13,
                "turn_type": "corner",
            },
            {
                "turn_number": 2,
                "name": "Turn 2-4 - The Esses",
                "start_pct": 0.15,
                "apex_pct": 0.20,
                "end_pct": 0.27,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - The Bus Stop / Inner Loop",
                "start_pct": 0.38,
                "apex_pct": 0.42,
                "end_pct": 0.47,
                "turn_type": "chicane",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - The Carousel",
                "start_pct": 0.48,
                "apex_pct": 0.52,
                "end_pct": 0.57,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - The Chute",
                "start_pct": 0.60,
                "apex_pct": 0.64,
                "end_pct": 0.67,
                "turn_type": "corner",
            },
            {
                "turn_number": 8,
                "name": "Turn 8 - The Toe",
                "start_pct": 0.68,
                "apex_pct": 0.72,
                "end_pct": 0.77,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 9,
                "name": "Turn 9 - The Heel",
                "start_pct": 0.79,
                "apex_pct": 0.83,
                "end_pct": 0.86,
                "turn_type": "corner",
            },
            {
                "turn_number": 10,
                "name": "Turn 10 - Turn 10",
                "start_pct": 0.87,
                "apex_pct": 0.90,
                "end_pct": 0.93,
                "turn_type": "corner",
            },
            {
                "turn_number": 11,
                "name": "Turn 11 - Final Corner",
                "start_pct": 0.94,
                "apex_pct": 0.96,
                "end_pct": 0.99,
                "turn_type": "corner",
            },
        ],
    },
    {
        "track_name": "monza_gp",
        "display_name": "Autodromo Nazionale Monza - Grand Prix",
        "length_m": 5793.0,
        "aliases": ["monza", "monza gp", "monza full", "autodromo nazionale monza"],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1-2 - Variante del Rettifilo",
                "start_pct": 0.16,
                "apex_pct": 0.19,
                "end_pct": 0.23,
                "turn_type": "chicane",
            },
            {
                "turn_number": 3,
                "name": "Turn 3 - Curva Grande (Curva Biassono)",
                "start_pct": 0.24,
                "apex_pct": 0.29,
                "end_pct": 0.34,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 4,
                "name": "Turn 4-5 - Variante della Roggia",
                "start_pct": 0.40,
                "apex_pct": 0.43,
                "end_pct": 0.47,
                "turn_type": "chicane",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - First Lesmo (Curva di Lesmo 1)",
                "start_pct": 0.50,
                "apex_pct": 0.53,
                "end_pct": 0.56,
                "turn_type": "corner",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - Second Lesmo (Curva di Lesmo 2)",
                "start_pct": 0.58,
                "apex_pct": 0.61,
                "end_pct": 0.65,
                "turn_type": "corner",
            },
            {
                "turn_number": 8,
                "name": "Turn 8-10 - Variante Ascari",
                "start_pct": 0.72,
                "apex_pct": 0.76,
                "end_pct": 0.81,
                "turn_type": "chicane",
            },
            {
                "turn_number": 11,
                "name": "Turn 11 - Curva Parabolica (Curva Alboreto)",
                "start_pct": 0.88,
                "apex_pct": 0.93,
                "end_pct": 0.98,
                "turn_type": "sweeper",
            },
        ],
    },
    {
        "track_name": "silverstone_gp",
        "display_name": "Silverstone Circuit - Grand Prix",
        "length_m": 5891.0,
        "aliases": ["silverstone", "silverstone gp", "silverstone grand prix"],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - Abbey",
                "start_pct": 0.03,
                "apex_pct": 0.05,
                "end_pct": 0.08,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 2,
                "name": "Turn 2 - Farm",
                "start_pct": 0.09,
                "apex_pct": 0.11,
                "end_pct": 0.13,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 3,
                "name": "Turn 3 - Village",
                "start_pct": 0.14,
                "apex_pct": 0.16,
                "end_pct": 0.18,
                "turn_type": "corner",
            },
            {
                "turn_number": 4,
                "name": "Turn 4 - The Loop",
                "start_pct": 0.19,
                "apex_pct": 0.21,
                "end_pct": 0.24,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - Aintree",
                "start_pct": 0.25,
                "apex_pct": 0.27,
                "end_pct": 0.30,
                "turn_type": "corner",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - Brooklands",
                "start_pct": 0.43,
                "apex_pct": 0.46,
                "end_pct": 0.49,
                "turn_type": "corner",
            },
            {
                "turn_number": 7,
                "name": "Turn 7 - Luffield",
                "start_pct": 0.50,
                "apex_pct": 0.53,
                "end_pct": 0.57,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 8,
                "name": "Turn 8 - Woodcote",
                "start_pct": 0.58,
                "apex_pct": 0.60,
                "end_pct": 0.62,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 9,
                "name": "Turn 9 - Copse",
                "start_pct": 0.67,
                "apex_pct": 0.69,
                "end_pct": 0.72,
                "turn_type": "corner",
            },
            {
                "turn_number": 10,
                "name": "Turn 10-14 - Maggotts, Becketts & Chapel",
                "start_pct": 0.74,
                "apex_pct": 0.78,
                "end_pct": 0.84,
                "turn_type": "chicane",
            },
            {
                "turn_number": 15,
                "name": "Turn 15 - Stowe",
                "start_pct": 0.90,
                "apex_pct": 0.93,
                "end_pct": 0.96,
                "turn_type": "corner",
            },
            {
                "turn_number": 16,
                "name": "Turn 16-18 - Vale & Club",
                "start_pct": 0.96,
                "apex_pct": 0.98,
                "end_pct": 0.99,
                "turn_type": "chicane",
            },
        ],
    },
    {
        "track_name": "redbull_ring_gp",
        "display_name": "Red Bull Ring - Grand Prix",
        "length_m": 4318.0,
        "aliases": ["red bull ring", "redbull ring", "redbullring", "spielberg", "oesterreichring"],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - Niki Lauda Kurve",
                "start_pct": 0.07,
                "apex_pct": 0.10,
                "end_pct": 0.14,
                "turn_type": "corner",
            },
            {
                "turn_number": 2,
                "name": "Turn 2 - Remus (Turn 3 Hairpin)",
                "start_pct": 0.28,
                "apex_pct": 0.32,
                "end_pct": 0.36,
                "turn_type": "hairpin",
            },
            {
                "turn_number": 3,
                "name": "Turn 3 - Rauch (Schlossgold)",
                "start_pct": 0.45,
                "apex_pct": 0.48,
                "end_pct": 0.52,
                "turn_type": "corner",
            },
            {
                "turn_number": 4,
                "name": "Turn 4 - Rauch / Würth Kurve",
                "start_pct": 0.57,
                "apex_pct": 0.60,
                "end_pct": 0.64,
                "turn_type": "sweeper",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - Rindt Kurve",
                "start_pct": 0.77,
                "apex_pct": 0.80,
                "end_pct": 0.84,
                "turn_type": "corner",
            },
            {
                "turn_number": 6,
                "name": "Turn 6 - Red Bull Mobile",
                "start_pct": 0.91,
                "apex_pct": 0.94,
                "end_pct": 0.98,
                "turn_type": "corner",
            },
        ],
    },
    {
        "track_name": "road_atlanta_full",
        "display_name": "Michelin Raceway Road Atlanta",
        "length_m": 4088.0,
        "aliases": ["road atlanta", "roadatlanta", "road atlanta full"],
        "turns": [
            {
                "turn_number": 1,
                "name": "Turn 1 - Turn 1",
                "start_pct": 0.05,
                "apex_pct": 0.08,
                "end_pct": 0.12,
                "turn_type": "corner",
            },
            {
                "turn_number": 2,
                "name": "Turn 2-4 - The Esses",
                "start_pct": 0.16,
                "apex_pct": 0.22,
                "end_pct": 0.29,
                "turn_type": "chicane",
            },
            {
                "turn_number": 5,
                "name": "Turn 5 - Turn 5",
                "start_pct": 0.32,
                "apex_pct": 0.36,
                "end_pct": 0.40,
                "turn_type": "corner",
            },
            {
                "turn_number": 6,
                "name": "Turn 6-7 - Turn 6 & 7",
                "start_pct": 0.44,
                "apex_pct": 0.48,
                "end_pct": 0.54,
                "turn_type": "corner",
            },
            {
                "turn_number": 10,
                "name": "Turn 10A-10B - The Chicane",
                "start_pct": 0.81,
                "apex_pct": 0.85,
                "end_pct": 0.89,
                "turn_type": "chicane",
            },
            {
                "turn_number": 12,
                "name": "Turn 12 - Final Downhill Sweeper",
                "start_pct": 0.92,
                "apex_pct": 0.95,
                "end_pct": 0.98,
                "turn_type": "sweeper",
            },
        ],
    },
]

for t in tracks:
    filename = f"{t['track_name']}.json"
    filepath = os.path.join(tracks_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(t, f, indent=2, ensure_ascii=False)
    print(f"Created {filepath}")
